### PR TITLE
Issue 8

### PR DESCRIPTION
**Pull request by alexharv074**

### CODE REVIEW

**Comment by alexharv074** [comment]
I've given up trying to run the tests locally unfortunately due to an issue I mentioned in another thread.  Seems like Travis CI is telling me that some tests failed?  Is the file it's complaining about really the README.md ... ?

**Comment by alexharv074** [comment]
Okay I've updated the tests but the Travis CI build is still failing.  Any idea what this could mean? https://travis-ci.org/hawknewton/puppet-pulp/jobs/53295996

**Comment by alexharv074** [comment]
Um, ping. :)

**Comment by hawknewton** [comment]
We either drop support for 1.8.7 or pin highline.  Give me a sec.

**Pull request merged**
